export const USER_REGISTER_REQUESTED = 'USER_REGISTER_REQUESTED'
export const USER_REGISTER_OK = 'USER_REGISTER_OK'
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

export const USER_LOGIN_REQUESTED = 'USER_LOGIN_REQUESTED'
export const USER_LOGIN_OK = 'USER_LOGIN_OK'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

export const USER_LOGOUT_REQUESTED = 'USER_LOGOUT_REQUESTED'
export const USER_LOGOUT_OK = 'USER_LOGOUT_OK'
export const USER_LOGOUT_ERROR = 'USER_LOGOUT_ERROR'

export const USER_SESSION_REQUESTED = 'USER_SESSION_REQUESTED'
export const USER_SESSION_YES = 'USER_SESSION_YES'
export const USER_SESSION_NO= 'USER_SESSION_NO'

export const ADD_ARTICLE = 'ADD_ARTICLE'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const GET_ARTICLE = 'GET_ARTICLE'

export const GET_ARTICLES_FROM_SERVER_REQUESTED = 'GET_ARTICLES_FROM_SERVER_REQUESTED'
export const GET_ARTICLES_FROM_SERVER_YES = 'GET_ARTICLES_FROM_SERVER_YES'
export const GET_ARTICLES_FROM_SERVER_ERROR = 'GET_ARTICLES_FROM_SERVER_ERROR'

export const APP_ERROR_CLEAR = 'APP_ERROR_CLEAR'